add a bootup command with weave networks

diff --git a/infra/infra b/infra/infra
--- a/infra/infra
+++ b/infra/infra
@@ -49,6 +49,34 @@ case ${command} in
     mkdir -p ${PWD}/data/couchdb
     mkdir -p ${PWD}/data/influxdb
     ;;
+  bootup)
+    echo "[bootup]: swarm advertise address - ${INFRA_SWARM_ADVERTISE_ADDR}"
+    docker swarm init --advertise-addr=${INFRA_SWARM_ADVERTISE_ADDR}
+
+    echo "[bootup]: make sure the network plugin 'weave' installed"
+    weave=weaveworks/net-plugin:latest_release
+    ensure_plugin_installed ${weave}
+    docker plugin disable ${weave} \
+      && docker plugin set ${weave} WEAVE_PASSWORD=1234 WEAVE_MULTICAST=1 \
+      && docker plugin enable ${weave}
+    if [[ $? ]]; then
+      echo "[bootup]: plugin launched"
+    else
+      echo "[bootup]: failed to enable the plugin ${weave}"
+      exit 1
+    fi
+
+    echo "[bootup]: creating mesh networks"
+    ensure_network 'infra-public' --driver=overlay --attachable
+    ensure_network 'infra-private' --driver=${weave} --attachable
+
+    echo "[bootup]: initialize data/storage folders"
+    mkdir -p ${PWD}/data/es
+    mkdir -p ${PWD}/data/traefik/cert
+    mkdir -p ${PWD}/data/couchdb
+    mkdir -p ${PWD}/data/influxdb
+    echo "[bootup]: ok"
+    ;;
   *)
     echo "info node id -- node id"
     ;;
